# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import enum_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SceneUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=50, null=None)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', enum_field.EnumField(enum_field.Enum(('M', 'Male'), ('F', 'Female')))),
            ],
        ),
    ]
